#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tugas_Besar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tugas_gede")]
	public partial class DataMotoClyfeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdata_user(data_user instance);
    partial void Updatedata_user(data_user instance);
    partial void Deletedata_user(data_user instance);
    partial void Insertdata_motor(data_motor instance);
    partial void Updatedata_motor(data_motor instance);
    partial void Deletedata_motor(data_motor instance);
    partial void Insertdata_pengembalian(data_pengembalian instance);
    partial void Updatedata_pengembalian(data_pengembalian instance);
    partial void Deletedata_pengembalian(data_pengembalian instance);
    partial void Insertdata_sewa(data_sewa instance);
    partial void Updatedata_sewa(data_sewa instance);
    partial void Deletedata_sewa(data_sewa instance);
    #endregion
		
		public DataMotoClyfeDataContext() : 
				base(global::Tugas_Besar.Properties.Settings.Default.tugas_gedeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataMotoClyfeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMotoClyfeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMotoClyfeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMotoClyfeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<data_user> data_users
		{
			get
			{
				return this.GetTable<data_user>();
			}
		}
		
		public System.Data.Linq.Table<data_motor> data_motors
		{
			get
			{
				return this.GetTable<data_motor>();
			}
		}
		
		public System.Data.Linq.Table<data_pengembalian> data_pengembalians
		{
			get
			{
				return this.GetTable<data_pengembalian>();
			}
		}
		
		public System.Data.Linq.Table<data_sewa> data_sewas
		{
			get
			{
				return this.GetTable<data_sewa>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data_user")]
	public partial class data_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_user;
		
		private string _username;
		
		private string _password;
		
		private string _role;
		
		private EntitySet<data_sewa> _data_sewas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    #endregion
		
		public data_user()
		{
			this._data_sewas = new EntitySet<data_sewa>(new Action<data_sewa>(this.attach_data_sewas), new Action<data_sewa>(this.detach_data_sewas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_user_data_sewa", Storage="_data_sewas", ThisKey="id_user", OtherKey="id_user")]
		public EntitySet<data_sewa> data_sewas
		{
			get
			{
				return this._data_sewas;
			}
			set
			{
				this._data_sewas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_data_sewas(data_sewa entity)
		{
			this.SendPropertyChanging();
			entity.data_user = this;
		}
		
		private void detach_data_sewas(data_sewa entity)
		{
			this.SendPropertyChanging();
			entity.data_user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data_motor")]
	public partial class data_motor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_motor;
		
		private string _nama_motor;
		
		private string _jenis_motor;
		
		private string _pabrikan_motor;
		
		private int _ukuran_mesin;
		
		private int _tahun_pembuatan;
		
		private string _plat_nomor;
		
		private string _status_motor;
		
		private EntitySet<data_sewa> _data_sewas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_motorChanging(int value);
    partial void Onid_motorChanged();
    partial void Onnama_motorChanging(string value);
    partial void Onnama_motorChanged();
    partial void Onjenis_motorChanging(string value);
    partial void Onjenis_motorChanged();
    partial void Onpabrikan_motorChanging(string value);
    partial void Onpabrikan_motorChanged();
    partial void Onukuran_mesinChanging(int value);
    partial void Onukuran_mesinChanged();
    partial void Ontahun_pembuatanChanging(int value);
    partial void Ontahun_pembuatanChanged();
    partial void Onplat_nomorChanging(string value);
    partial void Onplat_nomorChanged();
    partial void Onstatus_motorChanging(string value);
    partial void Onstatus_motorChanged();
    #endregion
		
		public data_motor()
		{
			this._data_sewas = new EntitySet<data_sewa>(new Action<data_sewa>(this.attach_data_sewas), new Action<data_sewa>(this.detach_data_sewas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_motor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_motor
		{
			get
			{
				return this._id_motor;
			}
			set
			{
				if ((this._id_motor != value))
				{
					this.Onid_motorChanging(value);
					this.SendPropertyChanging();
					this._id_motor = value;
					this.SendPropertyChanged("id_motor");
					this.Onid_motorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_motor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nama_motor
		{
			get
			{
				return this._nama_motor;
			}
			set
			{
				if ((this._nama_motor != value))
				{
					this.Onnama_motorChanging(value);
					this.SendPropertyChanging();
					this._nama_motor = value;
					this.SendPropertyChanged("nama_motor");
					this.Onnama_motorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_motor", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string jenis_motor
		{
			get
			{
				return this._jenis_motor;
			}
			set
			{
				if ((this._jenis_motor != value))
				{
					this.Onjenis_motorChanging(value);
					this.SendPropertyChanging();
					this._jenis_motor = value;
					this.SendPropertyChanged("jenis_motor");
					this.Onjenis_motorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pabrikan_motor", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string pabrikan_motor
		{
			get
			{
				return this._pabrikan_motor;
			}
			set
			{
				if ((this._pabrikan_motor != value))
				{
					this.Onpabrikan_motorChanging(value);
					this.SendPropertyChanging();
					this._pabrikan_motor = value;
					this.SendPropertyChanged("pabrikan_motor");
					this.Onpabrikan_motorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ukuran_mesin", DbType="Int NOT NULL")]
		public int ukuran_mesin
		{
			get
			{
				return this._ukuran_mesin;
			}
			set
			{
				if ((this._ukuran_mesin != value))
				{
					this.Onukuran_mesinChanging(value);
					this.SendPropertyChanging();
					this._ukuran_mesin = value;
					this.SendPropertyChanged("ukuran_mesin");
					this.Onukuran_mesinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tahun_pembuatan", DbType="Int NOT NULL")]
		public int tahun_pembuatan
		{
			get
			{
				return this._tahun_pembuatan;
			}
			set
			{
				if ((this._tahun_pembuatan != value))
				{
					this.Ontahun_pembuatanChanging(value);
					this.SendPropertyChanging();
					this._tahun_pembuatan = value;
					this.SendPropertyChanged("tahun_pembuatan");
					this.Ontahun_pembuatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plat_nomor", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string plat_nomor
		{
			get
			{
				return this._plat_nomor;
			}
			set
			{
				if ((this._plat_nomor != value))
				{
					this.Onplat_nomorChanging(value);
					this.SendPropertyChanging();
					this._plat_nomor = value;
					this.SendPropertyChanged("plat_nomor");
					this.Onplat_nomorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_motor", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string status_motor
		{
			get
			{
				return this._status_motor;
			}
			set
			{
				if ((this._status_motor != value))
				{
					this.Onstatus_motorChanging(value);
					this.SendPropertyChanging();
					this._status_motor = value;
					this.SendPropertyChanged("status_motor");
					this.Onstatus_motorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_motor_data_sewa", Storage="_data_sewas", ThisKey="id_motor", OtherKey="id_motor")]
		public EntitySet<data_sewa> data_sewas
		{
			get
			{
				return this._data_sewas;
			}
			set
			{
				this._data_sewas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_data_sewas(data_sewa entity)
		{
			this.SendPropertyChanging();
			entity.data_motor = this;
		}
		
		private void detach_data_sewas(data_sewa entity)
		{
			this.SendPropertyChanging();
			entity.data_motor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data_pengembalian")]
	public partial class data_pengembalian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pengembalian;
		
		private int _id_sewa;
		
		private System.DateTime _date_pengembalian;
		
		private System.TimeSpan _time_pengembalian;
		
		private string _status_pengembalian;
		
		private EntityRef<data_sewa> _data_sewa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pengembalianChanging(int value);
    partial void Onid_pengembalianChanged();
    partial void Onid_sewaChanging(int value);
    partial void Onid_sewaChanged();
    partial void Ondate_pengembalianChanging(System.DateTime value);
    partial void Ondate_pengembalianChanged();
    partial void Ontime_pengembalianChanging(System.TimeSpan value);
    partial void Ontime_pengembalianChanged();
    partial void Onstatus_pengembalianChanging(string value);
    partial void Onstatus_pengembalianChanged();
    #endregion
		
		public data_pengembalian()
		{
			this._data_sewa = default(EntityRef<data_sewa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pengembalian", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pengembalian
		{
			get
			{
				return this._id_pengembalian;
			}
			set
			{
				if ((this._id_pengembalian != value))
				{
					this.Onid_pengembalianChanging(value);
					this.SendPropertyChanging();
					this._id_pengembalian = value;
					this.SendPropertyChanged("id_pengembalian");
					this.Onid_pengembalianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sewa", DbType="Int NOT NULL")]
		public int id_sewa
		{
			get
			{
				return this._id_sewa;
			}
			set
			{
				if ((this._id_sewa != value))
				{
					if (this._data_sewa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_sewaChanging(value);
					this.SendPropertyChanging();
					this._id_sewa = value;
					this.SendPropertyChanged("id_sewa");
					this.Onid_sewaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_pengembalian", DbType="Date NOT NULL")]
		public System.DateTime date_pengembalian
		{
			get
			{
				return this._date_pengembalian;
			}
			set
			{
				if ((this._date_pengembalian != value))
				{
					this.Ondate_pengembalianChanging(value);
					this.SendPropertyChanging();
					this._date_pengembalian = value;
					this.SendPropertyChanged("date_pengembalian");
					this.Ondate_pengembalianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_pengembalian", DbType="Time NOT NULL")]
		public System.TimeSpan time_pengembalian
		{
			get
			{
				return this._time_pengembalian;
			}
			set
			{
				if ((this._time_pengembalian != value))
				{
					this.Ontime_pengembalianChanging(value);
					this.SendPropertyChanging();
					this._time_pengembalian = value;
					this.SendPropertyChanged("time_pengembalian");
					this.Ontime_pengembalianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_pengembalian", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string status_pengembalian
		{
			get
			{
				return this._status_pengembalian;
			}
			set
			{
				if ((this._status_pengembalian != value))
				{
					this.Onstatus_pengembalianChanging(value);
					this.SendPropertyChanging();
					this._status_pengembalian = value;
					this.SendPropertyChanged("status_pengembalian");
					this.Onstatus_pengembalianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_sewa_data_pengembalian", Storage="_data_sewa", ThisKey="id_sewa", OtherKey="id_sewa", IsForeignKey=true)]
		public data_sewa data_sewa
		{
			get
			{
				return this._data_sewa.Entity;
			}
			set
			{
				data_sewa previousValue = this._data_sewa.Entity;
				if (((previousValue != value) 
							|| (this._data_sewa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._data_sewa.Entity = null;
						previousValue.data_pengembalians.Remove(this);
					}
					this._data_sewa.Entity = value;
					if ((value != null))
					{
						value.data_pengembalians.Add(this);
						this._id_sewa = value.id_sewa;
					}
					else
					{
						this._id_sewa = default(int);
					}
					this.SendPropertyChanged("data_sewa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.data_sewa")]
	public partial class data_sewa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_sewa;
		
		private int _id_user;
		
		private int _id_motor;
		
		private System.DateTime _tanggal_sewa;
		
		private System.TimeSpan _waktu_sewa;
		
		private string _status_sewa;
		
		private EntitySet<data_pengembalian> _data_pengembalians;
		
		private EntityRef<data_motor> _data_motor;
		
		private EntityRef<data_user> _data_user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_sewaChanging(int value);
    partial void Onid_sewaChanged();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void Onid_motorChanging(int value);
    partial void Onid_motorChanged();
    partial void Ontanggal_sewaChanging(System.DateTime value);
    partial void Ontanggal_sewaChanged();
    partial void Onwaktu_sewaChanging(System.TimeSpan value);
    partial void Onwaktu_sewaChanged();
    partial void Onstatus_sewaChanging(string value);
    partial void Onstatus_sewaChanged();
    #endregion
		
		public data_sewa()
		{
			this._data_pengembalians = new EntitySet<data_pengembalian>(new Action<data_pengembalian>(this.attach_data_pengembalians), new Action<data_pengembalian>(this.detach_data_pengembalians));
			this._data_motor = default(EntityRef<data_motor>);
			this._data_user = default(EntityRef<data_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sewa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_sewa
		{
			get
			{
				return this._id_sewa;
			}
			set
			{
				if ((this._id_sewa != value))
				{
					this.Onid_sewaChanging(value);
					this.SendPropertyChanging();
					this._id_sewa = value;
					this.SendPropertyChanged("id_sewa");
					this.Onid_sewaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="Int NOT NULL")]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					if (this._data_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_motor", DbType="Int NOT NULL")]
		public int id_motor
		{
			get
			{
				return this._id_motor;
			}
			set
			{
				if ((this._id_motor != value))
				{
					if (this._data_motor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_motorChanging(value);
					this.SendPropertyChanging();
					this._id_motor = value;
					this.SendPropertyChanged("id_motor");
					this.Onid_motorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal_sewa", DbType="Date NOT NULL")]
		public System.DateTime tanggal_sewa
		{
			get
			{
				return this._tanggal_sewa;
			}
			set
			{
				if ((this._tanggal_sewa != value))
				{
					this.Ontanggal_sewaChanging(value);
					this.SendPropertyChanging();
					this._tanggal_sewa = value;
					this.SendPropertyChanged("tanggal_sewa");
					this.Ontanggal_sewaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waktu_sewa", DbType="Time NOT NULL")]
		public System.TimeSpan waktu_sewa
		{
			get
			{
				return this._waktu_sewa;
			}
			set
			{
				if ((this._waktu_sewa != value))
				{
					this.Onwaktu_sewaChanging(value);
					this.SendPropertyChanging();
					this._waktu_sewa = value;
					this.SendPropertyChanged("waktu_sewa");
					this.Onwaktu_sewaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_sewa", DbType="VarChar(50)")]
		public string status_sewa
		{
			get
			{
				return this._status_sewa;
			}
			set
			{
				if ((this._status_sewa != value))
				{
					this.Onstatus_sewaChanging(value);
					this.SendPropertyChanging();
					this._status_sewa = value;
					this.SendPropertyChanged("status_sewa");
					this.Onstatus_sewaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_sewa_data_pengembalian", Storage="_data_pengembalians", ThisKey="id_sewa", OtherKey="id_sewa")]
		public EntitySet<data_pengembalian> data_pengembalians
		{
			get
			{
				return this._data_pengembalians;
			}
			set
			{
				this._data_pengembalians.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_motor_data_sewa", Storage="_data_motor", ThisKey="id_motor", OtherKey="id_motor", IsForeignKey=true)]
		public data_motor data_motor
		{
			get
			{
				return this._data_motor.Entity;
			}
			set
			{
				data_motor previousValue = this._data_motor.Entity;
				if (((previousValue != value) 
							|| (this._data_motor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._data_motor.Entity = null;
						previousValue.data_sewas.Remove(this);
					}
					this._data_motor.Entity = value;
					if ((value != null))
					{
						value.data_sewas.Add(this);
						this._id_motor = value.id_motor;
					}
					else
					{
						this._id_motor = default(int);
					}
					this.SendPropertyChanged("data_motor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="data_user_data_sewa", Storage="_data_user", ThisKey="id_user", OtherKey="id_user", IsForeignKey=true)]
		public data_user data_user
		{
			get
			{
				return this._data_user.Entity;
			}
			set
			{
				data_user previousValue = this._data_user.Entity;
				if (((previousValue != value) 
							|| (this._data_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._data_user.Entity = null;
						previousValue.data_sewas.Remove(this);
					}
					this._data_user.Entity = value;
					if ((value != null))
					{
						value.data_sewas.Add(this);
						this._id_user = value.id_user;
					}
					else
					{
						this._id_user = default(int);
					}
					this.SendPropertyChanged("data_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_data_pengembalians(data_pengembalian entity)
		{
			this.SendPropertyChanging();
			entity.data_sewa = this;
		}
		
		private void detach_data_pengembalians(data_pengembalian entity)
		{
			this.SendPropertyChanging();
			entity.data_sewa = null;
		}
	}
}
#pragma warning restore 1591
